
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devpvc
  namespace: dbns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: datastore
  resources:
    requests:
      storage: 5Gi
